linuxdeepin/deepin-movie-reborn

src/common/mainwindow.cpp
refer to [https://github.com/linuxdeepin/deepin-movie-reborn/issues/26](https://github.com/linuxdeepin/deepin-movie-reborn/issues/26)
Thank you.
=> add *.smi support

README.md, src/common/actions.cpp, src/common/mainwindow.cpp, src/common/settings_translation.cpp, src/translations/deepin-movie.ts, src/widgets/burst_screenshots_dialog.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1269
=> chore: translation update.

src/common/mainwindow.cpp, src/libdmr/player_engine.h
https://github.com/linuxdeepin/developer-center/issues/927
=> feat: Drag and drop to load subtitle

src/resources/data/settings.json
=> fix: missing settings item added. Fixes crash on file open.

src/common/utility_x11.cpp
=> fix: workaround for QTBUG-76114.

src/libdmr/compositing_manager.cpp, src/libdmr/compositing_manager.h
=> fix: card0 may not enabled/usable

src/common/event_monitor.cpp, src/common/event_monitor.h, src/libdmr/online_sub.h
=> fix: sanitize includes.

src/backends/mpv/mpv_glwidget.h, src/backends/mpv/mpv_proxy.h, src/libdmr/compositing_manager.cpp, src/vendor/qthelper.hpp
doesn't build with latest mpv since 5.7.6.109
Log:
Issue: Closes #60
=> fix: build failed

src/vendor/presenter.cpp
修复dbus暂停后恢复问题
Bug: https://pms.uniontech.com/bug-view-131973.html
Log: 修复部分已知问题
=> fix: 修复dbus暂停恢复问题

src/CMakeLists.txt, src/common/mainwindow.cpp
=> fix: 社区版兼容性

src/common/mainwindow.cpp
=> fix: 去掉无用代码

src/CMakeLists.txt, src/common/mainwindow.cpp
修复全屏菜单状态异常问题
Bug: https://pms.uniontech.com/bug-view-134633.html
Log: 修复部分已知问题
=> fix: 修复全屏菜单状态异常问题

src/CMakeLists.txt, src/libdmr/filefilter.cpp, src/libdmr/filefilter.h, src/libdmr/gstutils.cpp, src/libdmr/gstutils.h
动态加载gstreamer
Log: 动态加载gstreamer
=> fix: 动态加载gstreamer

debian/control
修改control文件依赖
Log: 修改control文件依赖
=> fix: 修改control文件依赖

src/libdmr/player_engine.cpp
错误提示乱码修改
Bug: https://pms.uniontech.com/bug-view-138159.html
Log: 错误提示乱码修改
=> fix: 错误提示乱码修改

src/libdmr/player_engine.cpp
代码同步，错误提示乱码修改
Log: 代码同步，错误提示乱码修改
=> fix: 代码同步，错误提示乱码修改

src/libdmr/filefilter.cpp
修复影院导入压缩7Z文件至播放列表
Bug: https://pms.uniontech.com/bug-view-138793.html
Log: 修复影院导入压缩7Z文件至播放列表
=> fix: 修复影院导入压缩7Z文件至播放列表

src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp
Fix https://github.com/linuxdeepin/developer-center/issues/2250
- Drop drop-MPV_EVENT_TRACKS_CHANGED
- Change mpv_opengl_init_params
=> Fix build on git version of MPV

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/widgets/platform/platform_playlist_widget.cpp, src/widgets/platform/platform_volumeslider.cpp, src/widgets/playlist_widget.cpp, src/widgets/volumeslider.cpp
=> 修复bug 138165 110293

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h
对短视频滑动做累加处理
Bug: https://pms.uniontech.com/bug-view-122499.html
Log: 修复部分已知问题
=> fix: 短视频滑动无效

src/backends/mpv/mpv_proxy.cpp
龙芯5000模式使用gpu渲染
Bug: https://pms.uniontech.com/bug-view-128495.html
Log: 修复部分已知问题
=> fix: 修复龙芯5000显存泄露问题

src/backends/mediaplayer/qtplayer_glwidget.cpp, src/backends/mpv/mpv_glwidget.cpp, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/libdmr/player_engine.cpp, src/main.cpp, src/widgets/burst_screenshots_dialog.cpp, src/widgets/dmr_lineedit.cpp, src/widgets/url_dialog.cpp
图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片
Log: 图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片
=> fix: 图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片

src/backends/mediaplayer/qtplayer_glwidget.cpp, src/backends/mpv/mpv_glwidget.cpp, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/libdmr/player_engine.cpp, src/main.cpp, src/widgets/burst_screenshots_dialog.cpp, src/widgets/dmr_lineedit.cpp, src/widgets/url_dialog.cpp
图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片
Log: 图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片
=> fix: 修复bug 139401 图标与控制中心保持一致，url界面与dtk控件一致，去除深色背景图片

CMakeLists.txt, archlinux/PKGBUILD, src/CMakeLists.txt, src/vendor/presenter.cpp, tests/deepin-movie/stub/stub.h, tests/mpris_test.cc
=> feat: add archlinux build

src/backends/mediaplayer/qtplayer_proxy.cpp, src/libdmr/player_engine.cpp, src/libdmr/playlist_model.cpp, src/libdmr/playlist_model.h
修复cppcheck检查错误
Log: 修复cppcheck检查错误
=> fix: 修复cppcheck检查错误

src/libdmr/playlist_model.h
修复ut卡死
Bug: https://pms.uniontech.com/bug-view-144857.html
Log: 修复部分已知问题
=> fix: 修复ut卡死问题

src/libdmr/compositing_manager.cpp
ffmpeg主线华为omx硬解支持
Log: ffmpeg主线华为omx硬解支持
=> fix: ffmpeg主线华为omx硬解支持

debian/rules, src/vendor/presenter.cpp
修改函数
Bug: https://pms.uniontech.com/bug-view-146293.html
Log: 修复部分已知问题
=> fix: 修复arm平台编译错误

src/main.cpp
使用egl进行渲染
Bug: https://pms.uniontech.com/bug-view-141973.html
Log: 修复部分已知问题
=> fix: 修复ffmpeg环境下景嘉微崩溃问题

debian/changelog, src/common/mainwindow.cpp, src/libdmr/eventlogutils.cpp, src/libdmr/eventlogutils.h, src/libdmr/player_engine.cpp
=> feat: 添加数据埋点

debian/changelog, src/common/mainwindow.cpp
去除窗口状态改变时修改窗口大小代码，窗口显示在有效窗口之外修复显示
Log: 去除窗口状态改变时修改窗口大小代码，窗口显示在有效窗口之外修复显示
=> fix: 修复bug 147331 146929

src/common/mainwindow.cpp, src/libdmr/player_engine.cpp
=> fix: 数据埋点 添加应用版本号

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复影院音量过小问题

src/common/platform/platform_mainwindow.cpp
修复摩尔线程显卡窗口异常及焦点问题
Bug: https://pms.uniontech.com/bug-view-146535.html,
https://pms.uniontech.com/bug-view-146245.html
Log: 修复部分已知问题
=> fix: 修复摩尔线程显卡问题

src/libdmr/player_engine.cpp
暂时屏蔽除启动外的数据埋点
Log: 屏蔽除应用启动外的埋点
=> fix: 数据埋点功能屏蔽

src/libdmr/player_engine.cpp
Reverts linuxdeepin/deepin-movie-reborn#170
=> Revert "fix: 数据埋点功能屏蔽"

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
=> fix: 修复英特尔集显播放卡顿

src/common/platform/platform_mainwindow.cpp
修复arm平台打开应用未记录埋点数据问题
Log: 修复arm打开未记录数据问题
Bug: https://pms.uniontech.com/bug-view-152251.html
=> fix: 修复arm打开未记录数据问题

debian/changelog, src/libdmr/player_engine.cpp
播放网络文件时不上传是否播放成功
Log: 播放网络文件时不上传是否播放成功
=> fix: 播放网络文件时不上传是否播放成功

src/backends/mediaplayer/qtplayer_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/common/dmr_settings.cpp, src/main.cpp
=> feat: 景嘉微适配

src/dlna/dlnaHttpServer/qhttpresponse.cpp
=> fix: cppcheck 修改

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp
合入社区版缩略图显示代码
Log: 合入社区版缩略图显示代码
=> fix: 合入社区版缩略图显示代码

src/backends/mpv/mpv_proxy.cpp
龙芯5000 影院适配
Log: 龙芯5000 影院适配
/review
@wyu71
=> fix: 龙芯5000 影院适配

src/backends/mpv/mpv_proxy.cpp
修复欢迎与预览视频播放声音小问题
Log: 修复欢迎与预览视频播放声音小问题
=> fix: 修复欢迎与预览视频播放声音小问题

CMakeLists.txt, src/CMakeLists.txt, src/libdmr/CMakeLists.txt, src/libdmr/libdmr.pc.in
Log: use GNUInstallDirs in CmakeLists
https://github.com/linuxdeepin/developer-center/issues/3167
=> chore: use GNUInstallDirs in CmakeLists

tests/deepin-movie-platform/CMakeLists.txt, tests/deepin-movie/CMakeLists.txt
不应该使用 find_package(gui-private)，  gui-private 是 qmake 的东西
=> fix: dont use find_package(gui-private)

src/backends/mpv/mpv_proxy.cpp
修复5000景嘉微播放问题
Bug: https://pms.uniontech.com/bug-view-156449.html
Log: 修复部分已知问题
=> fix: 修复5000景嘉微播放问题

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
9200显卡不使用opengl进行渲染
Log: 修复部分已知问题
=> fix: 修复9200播放异常问题

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/widgets/mircastwidget.cpp, src/widgets/mircastwidget.h
添加当前投屏设备保存，防止刷新过程中数据越界
Bug: https://pms.uniontech.com/bug-view-160049.html,
https://pms.uniontech.com/bug-view-159955.html,
https://pms.uniontech.com/bug-view-159947.html
Log: 修复部分已知问题
=> fix: 修复投屏闪退问题

src/libdmr/utils.cpp, src/widgets/platform/platform_volumeslider.cpp, src/widgets/volumeslider.cpp
调整音量条位置
Bug: https://pms.uniontech.com/bug-view-161911.html
Log: 修复部分已知问题
=> fix: 修复音量条位置异常

src/dlna/dlnaHttpServer/qhttpconnection.cpp
=> fix: 修改cppcheck

src/libdmr/compositing_manager.cpp
=> fix: 修复芯动显卡硬解码问题

src/accessibility/ac-deepin-movie-define.h
=> fix: 开源合规修改

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
去除英特尔集显窗口绑定判断
Bug: https://pms.uniontech.com/bug-view-165659.html
Log: 修复部分已知问题
=> fix: 修复英特尔集显播放崩溃

src/common/platform/platform_mainwindow.cpp, src/widgets/platform/platform_movie_progress_indicator.cpp
修改窗口dialog属性
Bug: https://pms.uniontech.com/bug-view-168923.html
Log: 修复部分已知问题
=> fix: 修复多个窗口问题

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复x100硬解码异常

src/widgets/url_dialog.cpp, src/widgets/volumeslider.cpp
设置对话框固定大小
Bug: https://pms.uniontech.com/bug-view-126597.html,
https://pms.uniontech.com/bug-view-142093.html
Log: 修复部分已知问题
=> fix: 修复dialog不居中问题

src/backends/mpv/mpv_proxy.cpp
修复9200 7200驱动安装无法硬解码问题
Log: 修复9200 7200驱动安装无法硬解码问题
/review
@pengfeixx @feeengli
=> fix: 修复9200 7200驱动安装无法硬解码问题

src/backends/mpv/mpv_proxy.cpp
=> fix: 同步x100硬解码

src/common/platform/platform_mainwindow.cpp
优化mousemove事件进入流程
Bug: https://pms.uniontech.com/bug-view-170807.html
Log: 修复部分已知问题
=> fix: 修复窗口绑定模式下拖动卡顿

src/backends/mpv/mpv_proxy.cpp
去除gpu输出判断
Bug: https://pms.uniontech.com/bug-view-170243.html
Log: 修复部分已知问题
=> fix: 修复5000播放文件符泄露问题

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
设置默认样式
Bug: https://pms.uniontech.com/bug-view-155983.html
Log: 修复部分已知问题
=> fix: 修复按钮样式异常

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
添加setwindowtitle设置
Task: https://pms.uniontech.com/task-view-218117.html
Log: 修复部分已知问题
=> feat: 应用获取打开文件路径

src/libdmr/compositing_manager.cpp
增加芯动显卡和摩尔显卡适配
Log: 增加芯动显卡和摩尔显卡适配
/reiview
@wyu71 @feeengli @pengfeixx
=> fix: 增加芯动显卡和摩尔显卡适配

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h
去除多余设置的图标样式
Bug: https://pms.uniontech.com/bug-view-176415.html
Log: 修复部分已知问题
=> fix: 修复按钮样式异常问题

.tx/deepin.conf, debian/changelog
=> fix: 修改changlog

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复摩尔线程显卡硬解码异常问题

src/widgets/toolbox_proxy.cpp
=> fix: 修复缩略图异常问题

src/backends/mpv/mpv_proxy.cpp, src/backends/mpv/mpv_proxy.h, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
修复双击打开影院，再点击播放按钮卡住问题
Bug: https://pms.uniontech.com/bug-view-174949.html
Log: 修复双击打开影院，再点击播放按钮卡住问题
=> fix: 修复双击打开影院，再点击播放按钮卡住问题

patches/fix-build-failed.patch
=> fix: 修改玲珑pathch

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复sw硬解码问题

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp, src/widgets/toolbutton.cpp, src/widgets/toolbutton.h
点击打开或关闭隐藏tip
BUg: https://pms.uniontech.com/bug-view-184975.html
Log: 修复部分已知问题
=> fix: 修复tip不隐藏问题

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_volumeslider.cpp, src/widgets/toolbox_proxy.cpp, src/widgets/volumeslider.cpp
去除音量条动画
Bug: https://pms.uniontech.com/bug-view-155979.html
Log: 修复部分已知问题
=> fix: 去除音量条动画

src/common/platform/platform_mainwindow.cpp
添加文件名判断
Bug: https://pms.uniontech.com/bug-view-186897.html
Log: 修复部分已知问题
=> fix: 修复打开视频提示异常问题

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复龙芯5000无法播放问题

src/common/mainwindow.cpp
去除窗口移动代码
Bug: https://pms.uniontech.com/bug-view-171807.html
Log: 修复部分已知问题
=> fix: 修复waylnd窗口移动问题

src/widgets/mircastwidget.cpp
停止投屏后刷新按钮样式
Bug: https://pms.uniontech.com/bug-view-163757.html
Log: 修复部分已知问题
=> fix: 修复结束投屏后按钮样式异常问题

src/common/dmr_settings.cpp
修改配置条件
Bug: https://pms.uniontech.com/bug-view-192317.html
Log: 修复部分已知问题
=> fix: 修复5000下设置选项异常问题

src/common/mainwindow.cpp
进入休眠时不暂停播放
Bug: https://pms.uniontech.com/bug-view-192833.html
Log: 修复部分已知问题
=> fix: 修复压测未播放问题

debian/changelog
=> fix: 修改changelog

src/libdmr/player_engine.cpp
m900 avs2 avs3视频播放适配
Log: m900 avs2 avs3视频播放适配
=> fix: m900 avs2 avs3视频播放适配

src/common/mainwindow.cpp
=> fix: 修复迷你模式缩放问题

src/backends/mpv/mpv_glwidget.cpp
去除wayland全屏下顶点绘制
Bug: https://pms.uniontech.com/bug-view-196087.html
Log: 修复部分已知问题
=> fix: 修复wayland下全屏顶点问题

src/widgets/volumeslider.cpp
增加音量初始化延迟
Bug: https://pms.uniontech.com/bug-view-158827.html
Log: 修复部分已知问题
=> fix: 修复提示时间短问题

src/backends/mpv/mpv_proxy.cpp
=> fix: xd 解码适配

src/libdmr/compositing_manager.cpp
修改格兰菲显卡为窗口绑定模式
Bug: https://pms.uniontech.com/bug-view-199385.html
Log: 修复部分已知问题
=> fix: 修复格兰菲显卡音量条控件显示异常问题

src/backends/mpv/mpv_proxy.cpp
=> fix: 硬解同步景嘉微解码方式

src/common/platform/platform_mainwindow.cpp, src/common/platform/platform_mainwindow.h
添加解锁后的延迟操作
Bug: https://pms.uniontech.com/bug-view-202035.html
Log: 修复部分已知问题
=> fix: 修复唤醒后音量变大问题

src/common/platform/platform_mainwindow.cpp
=> fix: 修复亿道退出卡死问题

src/common/mainwindow.cpp
=> fix: 添加pgw判断

src/widgets/platform/platform_volumeslider.cpp
修改音量取消静音
Bug: https://pms.uniontech.com/bug-view-204197.html
Log: 修复部分已知问题
=> fix: 修复修改音量未取消静音

assets/org.deepin.movie.minimode.json, debian/deepin-movie.install, src/CMakeLists.txt, src/common/mainwindow.cpp
Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
=> feat: hw机型判断适配dconfig

src/CMakeLists.txt
=> fix: 修复在低版本打包失败问题

src/libdmr/compositing_manager.cpp
修改软解方案规避
Bug: https://pms.uniontech.com/bug-view-209215.html
Log: 修复部分已知问题
=> fix: 修复休眠唤醒卡顿

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp
去除更新缩略图图片的时候更新位置，保证更新位置单一入口
Log: 修复部分已知问题
=> fix: 修复缩略图跳动问题

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复获取版本错误问题

src/backends/mpv/mpv_proxy.cpp
添加loongarch gpu输出
Bug: https://pms.uniontech.com/bug-view-214153.html
Log: 修复部分已知问题
=> fix: 修复龙芯播放视频卡顿

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复兆芯显卡下部分视频无法硬解码问题

src/common/platform/platform_mainwindow.cpp
Log: Constraints on mouse wheel distance outliers to keep the m_iAngLeDelta parameter in the appropriate range.
=> fix: Volume abnormal when screen is flipped

src/main.cpp
JJW7201不支持egl，去除相关设置
Log: 修复部分已知问题
=> fix: 修复JJW7201无法播放问题

src/common/dmr_settings.cpp, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/widgets/burst_screenshots_dialog.cpp, src/widgets/mircastwidget.cpp, src/widgets/notification_widget.cpp, src/widgets/platform/platform_playlist_widget.cpp, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/platform/platform_volumeslider.cpp, src/widgets/playlist_widget.cpp, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h, src/widgets/url_dialog.cpp, src/widgets/volumeslider.cpp
=> feat: 紧凑模式适配

src/backends/mpv/mpv_proxy.cpp
=> fix: 修复天翼云下播放卡死

src/common/platform/platform_mainwindow.cpp
修改龙芯5000平台不设置全屏控件
Bug: https://pms.uniontech.com/bug-view-223241.html
Log: 修复部分已知问题
=> fix: 修复紧凑模式闪退

src/backends/mpv/mpv_glwidget.cpp
优化4k60祯视频全屏闪黑屏显示
Bug: https://pms.uniontech.com/bug-view-221447.html
Log: 优化4k60祯视频全屏闪黑屏显示
=> fix: 优化4k60祯视频全屏闪黑屏显示

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
=> fix: 修复大屏播放卡顿问题

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
修复播放卡顿问题
Bug: https://pms.uniontech.com/bug-view-223835.html
log: 修复播放卡顿问题
=> fix: 添加loongarch直接渲染判断方式，修复播放卡顿问题

src/widgets/url_dialog.cpp
修改url界面的提示和输入框距离为10px
Bug: https://pms.uniontech.com/bug-view-155981.html
Log: 修改url界面的提示和输入框距离
=> fix: 修改url界面的提示和输入框距离

src/backends/mpv/mpv_glwidget.cpp
修复wayland下闪黑屏
Bug: https://pms.uniontech.com/bug-view-225881.html
Log: 修复wayland下闪黑屏
=> fix: 修复wayland下闪黑屏

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/widgets/platform/platform_playlist_widget.cpp, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/playlist_widget.cpp, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h
修复点击全屏后点击播放列表，界面显示有空白，继续点击播放列表空白一直存在
Log: 修复点击全屏后点击播放列表，界面显示有空白，继续点击播放列表空白一直存在
Bug: https://pms.uniontech.com/bug-view-225507.html
=> fixed: 点击全屏后点击播放列表，界面显示有空白，继续点击播放列表空白一直存在

debian/control
目前可以通过降低libunwind-dev的版本在新的ffmpeg环境下编译通过，但是运行依赖被写死，需要手动更新。
log:
=> chore:Update control to adapt to the new version of ffmpeg

debian/changelog
change log 5.10.37.
Log: change log 5.10.37.
=> fix: change log 5.10.37.

assets/deepin-movie.json
=> fix: update text

src/main.cpp
修复ai冷启动影院，未自动播放播放列表中的视频
Bug: https://pms.uniontech.com/bug-view-232419.html
Log: 修复ai冷启动影院，未自动播放播放列表中的视频
=> fix: 修复ai冷启动影院，未自动播放播放列表中的视频

src/backends/mpv/mpv_proxy.cpp
同步天翼云修复至主线，添加参数配置
Log: 修复部分已知问题
=> fix: 同步天翼云修复至主线

src/widgets/platform/platform_toolbox_proxy.cpp
arm/loongarch 修复初始化进度条中的缩略图时闪现黑色条纹
Log: arm/loongarch 修复初始化进度条中的缩略图时闪现黑色条纹
=> fix: arm/loongarch 修复初始化进度条中的缩略图时闪现黑色条纹

debian/changelog
changelog 5.10.39
Log: changelog 5.10.39
=> fix: changelog 5.10.39

debian/control, src/backends/mpv/mpv_proxy.cpp
修改影院硬件判断流程，将硬件解码能力判断放入gpuinfo中
Log: 修复部分已知问题
=> fix: 修改影院硬件判断流程

debian/control, src/backends/mpv/mpv_proxy.cpp
Reverts linuxdeepin/deepin-movie-reborn#399
=> Revert "fix: 修改影院硬件判断流程"

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
=> fix: 适配凌久微显卡

src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/backends/mpv/mpv_proxy.h, src/libdmr/compositing_manager.cpp
The MPV database name change is fixed
Bug: https://pms.uniontech.com/bug-view-237377.html
=> fix: The MPV database name change is fixed

src/libdmr/compositing_manager.cpp
jm7200支持egl异常,并且不支持硬解码,修改窗口绑定模式
Bug: https://pms.uniontech.com/bug-view-235711.html
Log: 修复部分已知问题
=> fix: 修复jm显卡播放闪退问题

debian/changelog
changelog 5.10.40
Log: changelog 5.10.40
=> fix: changelog 5.10.40

src/backends/mpv/mpv_proxy.cpp
The error of getting the path is fixed
=> fix: The error of getting the path is fixed

src/libdmr/compositing_manager.cpp
在bug单指出的设备和镜像，使用默认配置 hwdec=auto,
vo=gpu 不能正确输出.
对涉及的550系列显卡调整配置, 指定 hwdec=vaapi,vo=gpu.
对bug单测试集和多个视频格式验证, 暂未发现影响.
* 注意:启动时调用,会影响启动性能
Log: 修复部分设备播放hevc视频黑屏的问题
Bug: https://pms.uniontech.com/bug-view-234565.html
=> fix: 修复部分设备播放hevc视频黑屏的问题

debian/changelog
=> fix: tag 6.0.6

src/common/platform/platform_mainwindow.cpp, src/widgets/platform/platform_notification_widget.cpp
消息提示框显示时，判断之上的窗口是否存在遮挡，遮挡时不显示消息提示框
Bug: https://pms.uniontech.com/bug-view-228787.html
Log: 修复部分已知问题
=> fix: 修复消息提示框问题

src/libdmr/player_engine.cpp, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp
修改视频判断为视频流进行判断
Bug: https://pms.uniontech.com/bug-view-239817.html
Log: 修复部分已知问题
=> fix: 修复视频打开无画面问题

src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp
libdmr桌面视频壁纸
Log: libdmr桌面视频壁纸
=> fix: libdmr桌面视频壁纸

src/common/dmr_settings.cpp
=> fix: 修复模糊测试缺陷

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
退出时等待文件写入完成后再退出
Bug: https://pms.uniontech.com/bug-view-242507.html
Log: 修复部分已知问题
=> fix: 修复退出时音量未保存问题

debian/changelog
New version 5.10.46
Log: New version 5.10.46
=> fix: New version 5.10.46

src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp
fix get thumbnail error on hdpi devices
=> fix: get thumbnail error on hdpi devices

src/backends/mpv/mpv_proxy.cpp, src/libdmr/playlist_model.cpp
yuv444p格式使用软解码
Bug: https://pms.uniontech.com/bug-view-247589.html
Log: yuv444p格式使用软解码
=> fix: yuv444p格式使用软解码

src/backends/mpv/mpv_proxy.cpp, src/widgets/platform/platform_notification_widget.cpp
sw jmgpu硬解码适配
Bug: https://pms.uniontech.com/bug-view-240393.html
Log: sw jmgpu硬解码适配
=> fix: sw jmgpu硬解码适配

debian/changelog, src/backends/mpv/mpv_proxy.cpp
根据适配邮件调整HW机型的匹配方式
Log: 调整部分解码问题
Bug: https://pms.uniontech.com/bug-view-249087.html
chore: Bump version to 5.10.48
=> fix: 调整机型检测策略，更新changelog

debian/changelog
=> fix: tag 6.0.7 (#442)

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, translations/deepin-movie_bo.ts, translations/deepin-movie_ug.ts, translations/deepin-movie_zh_CN.ts, translations/deepin-movie_zh_HK.ts, translations/deepin-movie_zh_TW.ts
修复从自定义切制软硬解码后保存失败问题
Log: 修复部分已知问题
=> fix: 修复设置项保存失败问题

src/common/mainwindow.cpp
=> fix: 修复wayland下设置项异常问题

src/common/dmr_settings.cpp
修改wayland下选项为空问题
Log: 修复部分已知问题
=> fix: 修复wayland下选项为空问题

src/backends/mpv/mpv_proxy.cpp
龙芯5000为设置解码参数
Bug: https://pms.uniontech.com/bug-view-252763.html
Log: 修复部分已知问题
=> fix: rx550显卡下设置自动异常

src/libdmr/playlist_model.cpp, src/libdmr/playlist_model.h
=> fix: 头文件隐藏缩略图接口

src/backends/mpv/mpv_proxy.cpp
Fix the smearing screen of the mega core
Bug: https://pms.uniontech.com/bug-view-254087.html
=> fix: Fix the smearing screen of the mega core

debian/control
=> fix: Remove invalid dependencies

src/widgets/platform/platform_animationlabel.cpp, src/widgets/platform/platform_animationlabel.h
修复视频暂停/播放提示会透过文件显示问题
Bug: https://pms.uniontech.com/bug-view-255849.html
Log: 修复视频暂停/播放提示会透过文件显示问题
=> fix: 修复视频暂停/播放提示会透过文件显示问题

src/widgets/platform/platform_volumeslider.cpp, src/widgets/volumeslider.cpp
Reduce volume delay time at startup
Bug: https://pms.uniontech.com/bug-view-255921.html
=> fix: Fixed mute start-up squeak

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
the mircast window display in error place
Bug: https://pms.uniontech.com/bug-view-255847.html
Log: Fixed the mircast window display in error place
=> fix: the mircast window display in error place

src/libdmr/gstutils.cpp
Modified to use the data directly
=> fix: Fixed pointer usage errors

src/widgets/platform/platform_volumeslider.cpp
Fixed abnormal volume interaction
=> fix: Fixed abnormal volume interaction

src/common/mainwindow.cpp
Fix possible crashes caused by mouse release events
Log: Fix possible crashes caused by mouse release events
=> fix: Fix possible crashes caused by mouse release events

debian/control, src/common/dmr_settings.cpp, src/common/platform/platform_thumbnail_worker.cpp, src/common/platform/platform_thumbnail_worker.h, src/common/thumbnail_worker.cpp, src/common/thumbnail_worker.h, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h
Remove Thumbnailer dependency
Log: Remove Thumbnailer dependency
=> fix: Remove Thumbnailer dependency

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
修复双屏切换影院界面无法正常显示问题
Bug: https://pms.uniontech.com/bug-view-257239.html
Log: 修复双屏切换影院界面无法正常显示问题
=> fix: 修复双屏切换影院界面无法正常显示问题

debian/control, src/common/dmr_settings.cpp, src/common/platform/platform_thumbnail_worker.cpp, src/common/platform/platform_thumbnail_worker.h, src/common/thumbnail_worker.cpp, src/common/thumbnail_worker.h, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/platform/platform_toolbox_proxy.h, src/widgets/toolbox_proxy.cpp, src/widgets/toolbox_proxy.h
This reverts commit bd46423858a01b6062759b399d9c895cc8bafde2.
=> Revert "fix: Remove Thumbnailer dependency (#473)"

debian/changelog
changelog 6.0.9.
Log: changelog 6.0.9.
=> fix: changelog 6.0.9.

src/CMakeLists.txt, src/libdmr/CMakeLists.txt
adapt V25 linglong.yaml
Log: adapt V25 linglong.yaml
=> feat: adapt V25 linglong.yaml

src/backends/mpv/mpv_proxy.cpp
adapt the new version of libmpv 'loadfile'
Log: adapt the new version of libmpv 'loadfile'
Bug: https://pms.uniontech.com/bug-view-261771.html
=> fix: fix the new 'loadfile' api

examples/test/CMakeLists.txt, src/CMakeLists.txt, src/libdmr/CMakeLists.txt, src/libdmr/compositing_manager.cpp
adapt libPath on V25 linglong
Log: adapt libPath on V25 linglong
=> fix: adapt libPath on V25 linglong

CMakeLists.txt, examples/test/CMakeLists.txt, src/CMakeLists.txt, src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/backends/mpv/mpv_proxy.h, src/common/hwdec_probe.cpp, src/common/platform/platform_thumbnail_worker.cpp, src/common/thumbnail_worker.cpp, src/common/thumbnail_worker.h, src/libdmr/CMakeLists.txt, src/libdmr/compositing_manager.cpp, src/libdmr/compositing_manager.h, src/libdmr/eventlogutils.cpp, src/libdmr/filefilter.cpp, src/libdmr/filefilter.h, src/libdmr/gstutils.cpp, src/libdmr/gstutils.h, src/libdmr/playlist_model.cpp, src/libdmr/playlist_model.h, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp, src/widgets/toolbutton.h
adapt V25 linglong
Log: adapt V25 linglong
=> adapt V25 linglong

src/backends/mpv/mpv_proxy.cpp
compile problem
Log: compile problem
=> fix: compile problem

debian/changelog
changelog 6.0.10.
Log: changelog 6.0.10.
=> fix: changelog 6.0.10.

CMakeLists.txt, examples/test/CMakeLists.txt, src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/common/hwdec_probe.cpp, src/common/platform/platform_thumbnail_worker.cpp, src/common/thumbnail_worker.cpp, src/libdmr/compositing_manager.cpp, src/libdmr/compositing_manager.h, src/libdmr/filefilter.cpp, src/libdmr/filefilter.h, src/libdmr/gstutils.cpp, src/libdmr/playlist_model.cpp, src/widgets/platform/platform_toolbox_proxy.cpp, src/widgets/toolbox_proxy.cpp
Adapt V25 linglong
Log: Adapt V25 linglong
=> feat: Adapt V25 linglong

debian/control
Fixed the Community Edition dependency issue
Log: Fixed the Community Edition dependency issue
=> fix: Fixed the Community Edition dependency issue

debian/control
Fixed the ffmpeg dependency issue
Log: Fixed the ffmpeg dependency issue
=> fix: Fixed the ffmpeg dependency issue

src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/backends/mpv/mpv_proxy.h, src/libdmr/compositing_manager.cpp, src/main.cpp
Fixed the issue of dynamic library references
Log: Fixed the issue of dynamic library references
=> fix: Fixed the issue of dynamic library references

debian/control
加入推荐依赖va-driver-all
Bug: https://pms.uniontech.com/bug-view-266169.html https://pms.uniontech.com/bug-view-246323.html
Log: 加入推荐依赖va-driver-all
=> fix: 加入推荐依赖va-driver-all

src/main.cpp
movie treeland adaptation
Log: movie treeland adaptation
=> fix: movie treeland adaptation

assets/resources/data/lowEffectSettings.json, assets/resources/data/settings.json, src/backends/mpv/mpv_glwidget.cpp, src/backends/mpv/mpv_proxy.cpp, src/common/dmr_settings.cpp, src/common/mainwindow.cpp, src/common/mainwindow.h, src/common/platform/platform_mainwindow.cpp, src/common/platform/platform_mainwindow.h, src/common/settings_translation.cpp, src/libdmr/compositing_manager.cpp, src/libdmr/playlist_model.cpp, src/libdmr/playlist_model.h, src/main.cpp, src/widgets/toolbutton.h, translations/deepin-movie.ts, translations/deepin-movie_zh_CN.ts
pick up loss merge of release 1070
Log: pick up loss merge of release 1070
=> fix: pick up loss merge of release 1070

src/backends/mpv/mpv_proxy.cpp
fix the decoding select logic
Bug: https://pms.uniontech.com/bug-view-269827.html
Log: fix the decoding select logic
=> fix: the decoding select logic

src/backends/mpv/mpv_proxy.cpp, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/libdmr/compositing_manager.cpp, src/libdmr/utils.cpp, src/libdmr/utils.h, src/main.cpp, src/widgets/toolbox_proxy.cpp
cmd modify
Task:https://pms.uniontech.com/task-view-361907.html Log: cmd modify
=> fix: cmd modify

assets/resources/data/lowEffectSettings.json, assets/resources/data/settings.json, src/common/dmr_settings.cpp, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
fix the display UI logic, use flat to display
Log: fix the display UI logic
Bug: https://pms.uniontech.com/bug-view-272645.html
=> fix: the display UI logic

translations/deepin-movie_zh_CN.ts
fix the translations of task
Log: fix the translations of task
Bug: https://pms.uniontech.com/task-view-359615.html
=> fix: the translations of task

src/backends/mpv/mpv_proxy.cpp, src/libdmr/utils.cpp, src/libdmr/utils.h
切换默认link
Bug: https://pms.uniontech.com/bug-view-273295.html
Log: 切换默认link
=> fix: 切换默认link

arm64/linglong.yaml, deploy_dep, linglong.yaml
Sync the id version as deb version, and slimming down the linglong layer package.
Log: Linglong installation package slimming down.
=> chore: [linglong]The installation package slimming down

debian/changelog, deploy_dep
v5.15.3 release.
Log: v5.15.3 release.
=> chore: [tag] new version 5.15.3

arm64/linglong.yaml, linglong.yaml
Update linglong version.
Log: Update linglong version
=> chore: Update linglong version

src/common/dmr_settings.cpp, src/main.cpp
fix the professional mode log output info
Log: fix the professional mode log output info
https://pms.uniontech.com/bug-view-276395.html
=> fix: the professional mode log output info

src/common/mainwindow.cpp, src/common/mainwindow.h
修复视频窗口最大化，规避插拔屏窗口显示问题
Bug: https://pms.uniontech.com/bug-view-278557.html
Bug: https://pms.uniontech.com/bug-view-278559.html
Log: 修复视频窗口最大化，规避插拔屏窗口显示问题
=> fix: 修复视频窗口最大化，规避插拔屏窗口显示问题

src/backends/mpv/mpv_proxy.cpp
适配硬解码
Bug: https://pms.uniontech.com/bug-view-283187.html
Log: 适配硬解码
=> fix: 适配硬解码

arm64/linglong.yaml, debian/changelog, linglong.yaml, src/main.cpp, tests/deepin-movie-platform/application.cpp, tests/deepin-movie/application.cpp
remove kwayland-shell env
Log: remove kwayland-shell env
=> fix: remove kwayland-shell env

src/backends/mpv/mpv_proxy.cpp, src/libdmr/compositing_manager.cpp
修改RX550显卡默认走绑定窗口方式
Log: 修改RX550显卡默认走绑定窗口方式
Bug: https://pms.uniontech.com/bug-view-283671.html
=> fix: 修改RX550显卡默认走绑定窗口方式

src/backends/mpv/mpv_proxy.cpp, src/common/mainwindow.cpp
修复插拔屏后窗口显示异常问题
Bug: https://pms.uniontech.com/bug-view-278557.html
https://pms.uniontech.com/bug-view-278547.html
Log: 修复插拔屏后窗口显示异常问题
=> fix: 修复插拔屏后窗口显示异常问题

assets/resources/data/GstSettings.json, assets/resources/data/lowEffectSettings.json, assets/resources/data/settings.json, src/backends/mpv/mpv_glwidget.cpp, src/common/dmr_settings.cpp, src/common/dmr_settings.h, src/common/mainwindow.cpp, src/common/mainwindow.h, src/common/platform/platform_mainwindow.cpp, src/common/platform/platform_mainwindow.h, src/common/settings_translation.cpp, translations/deepin-movie_zh_CN.ts, translations/deepin-movie_zh_HK.ts, translations/deepin-movie_zh_TW.ts
影院加界面开关处理“全屏时显示倒计时”，开关默认为关
Task: https://pms.uniontech.com/task-view-369309.html
Log: 影院加界面开关处理“全屏时显示倒计时”，开关默认为关
=> fix: 影院加界面开关处理“全屏时显示倒计时”，开关默认为关

arm64/linglong.yaml, linglong.yaml
Update linglong.yaml for new runtime.
Log: Update linglong.yaml for new runtime
=> chore: update linglong.yaml for new runtime

src/backends/mpv/mpv_proxy.cpp
Fixed the ARM playback crash issue
Bug: https://pms.uniontech.com/bug-view-289613.html
Log: Fixed the ARM playback crash issue
=> fix: Fixed the ARM playback crash issue

.reuse/dep5, com.deepin.movie.service
Adapt to the new version of linglong.
Log: Adapt to the new version of linglong.
Task: https://pms.uniontech.com/task-view-369975.html
=> chore: Adapt to the new version of linglong

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 5.15.10
Log: Bump version to 5.15.10
=> chore: Bump version to 5.15.10

debian/control
=> fix: control change

src/libdmr/compositing_manager.cpp
Fix the video preview issue
Log: Fix the video preview issue
=> fix: Fix the video preview issue

src/configs/json/org_deepin_movie_minimode.hpp
- Add org_deepin_movie_minimode class for mini mode handling
- Add miniModeSpecialHandling property and related signals
- Implement DConfig integration for configuration persistence
Log: add mini mode special handling configuration
=> chore: add mini mode special handling configuration

src/common/volumemonitoring.cpp, src/widgets/platform/platform_volumeslider.cpp, src/widgets/volumeslider.cpp
dbus名称存在差异，导致访问等待
超时卡住
Log：修复启动影院卡住的问题
=> fix: 修复启动影院卡住的问题

src/common/sysutils.cpp
Fixed video preview failure
Log: Fixed video preview failure
=> fix: Fixed video preview failure

src/common/mainwindow.cpp
loogn64 quit fail
Log: loogn64 quit fail
=> fix: loogn64 quit fail

src/common/platform/platform_mainwindow.cpp
loogn64 mpv ui exit fail
Log： loogn64 mpv ui exit fail
=> fix: loogn64 mpv ui exit fail

src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp, src/main.cpp
Fix unable to automatically restart
Bug: https://pms.uniontech.com/bug-view-300705.html
Log: Fix unable to automatically restart
=> fix: Fix unable to automatically restart

debian/control, src/common/mainwindow.cpp, src/common/platform/platform_mainwindow.cpp
[fix: Fix the issue of xprop not being installed]
Fix the issue of xprop not being installed
Bug: https://pms.uniontech.com/bug-view-282535.html
Log: Fix the issue of xprop not being installed
[fix: Fix the issue of unable to open the folder]
Fix the issue of unable to open the folder
Bug: https://pms.uniontech.com/bug-view-280979.html
Log: Fix the issue of unable to open the folder
=> fix: Fix the issue of xprop not being installed

arm64/linglong.yaml, debian/changelog, deploy_dep, install_dep, linglong.yaml, loong64/linglong.yaml
Update linglong.yaml for qt6.8 runtime.
Log: Update linglong.yaml for qt6.8 runtime
=> chore: update linglong.yaml for qt6.8 runtime

src/backends/mpv/mpv_proxy.cpp
Fixed the issue that audio options were not available
Bug: https://pms.uniontech.com/bug-view-282559.html
Log: Fixed the issue that audio options were not available
=> fix: Fixed the issue that audio options were not available

src/backends/mpv/mpv_proxy.cpp, src/common/platform/platform_mainwindow.cpp
修复不能点击界面暂停问题
Bug: https://pms.uniontech.com/bug-view-298959.html
Log: 修复不能点击界面暂停问题
=> fix: 修复不能点击界面暂停问题

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, src/common/mainwindow.cpp, src/common/mainwindow.h
Fixed the crash issue of theater playback
Log: Fixed the crash issue of theater playback
=> fix: Fixed the crash issue of theater playback

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, translations/deepin-movie_zh_CN.ts, translations/deepin-movie_zh_HK.ts, translations/deepin-movie_zh_TW.ts
update translation
Log: update translation
=> chore: update translation
