- src/widgets/toolbox_proxy.cpp
wrong window flags of thumbnail preview window causes dock to
show up even if the player's in fullscreen mode.
see https://github.com/linuxdeepin/developer-center/issues/1157
> fix: thumbnail previewer caused dock show up

- src/libdmr/playlist_model.cpp
It seems that the version should not be restricted
Log:
Issue: Closes #59
> fix: wrong ffmpeg version check

- src/common/mainwindow.cpp
> fix: the height for selectableedit on settings dialog

- src/common/mainwindow.cpp
去除titlebar的setEnable，在关闭函数中处理
Bug: https://pms.uniontech.com/bug-view-129205.html
Log: 修复部分已知问题
> fix: 修复连拍最小化后无法关闭问题

- src/libdmr/filefilter.cpp
- tests/deepin-movie/common/test_mainwindow.cpp
修复本地视频名称上包含{}时，影院无法播放视频
Log: 调用ffmpeg接口检查本地视频文件是否可播放时，文件路径转换为本地路径
> fix: 修复本地视频名称上包含{}时，影院无法播放视频

- src/libdmr/utils.cpp
播放列表右键在文件管理中显示时，未选中当前文件
Bug: https://pms.uniontech.com/bug-view-139405.html
Log: 播放列表右键在文件管理中显示时，未选中当前文件
> fix: 修复播放列表右键在文件管理中显示时，未选中当前文件

- src/widgets/titlebar.cpp
影院图标没有跟随控制中心实时变化
Bug: https://pms.uniontech.com/bug-view-139401.html
Log: 修复影院图标没有跟随控制中心实时变化
> fix: 修复影院图标没有跟随控制中心实时变化

- src/widgets/platform/platform_volumeslider.cpp
使用播放引擎静音时因为缓存原因不能立即静音，增加系统应用静音操作。
Bug: https://pms.uniontech.com/bug-view-126591.html
Log: 功能修复
> fix: bug 126591

- src/common/mainwindow.cpp
主窗口resize时更新音量条控件位置
Bug: https://pms.uniontech.com/bug-view-144131.html
Log: 修复部分已知问题
> fix: 修复音量条控件位置异常

- src/backends/mpv/mpv_proxy.cpp
- src/libdmr/playlist_model.cpp
龙芯5000不使用gpuinfo探测
Bug: https://pms.uniontech.com/bug-view-134177.html
Log: 修复部分已知问题
> fix: 修复龙芯5000连续播放卡死

- src/CMakeLists.txt
Log: Use as-needed to enhance compatibility with linker
Signed-off-by: Han Gao <rabenda.cn@gmail.com>
> fix: use as-needed instead of as-need

- src/libdmr/player_engine.cpp
- src/libdmr/player_widget.cpp
139163 【文管5.6】【S6】【5.6.3.8】【N】快捷方式的视频拷贝至保险箱,空格预览无法自动播放
原因：PlayerWidget::play播放函数中，首先调用添加播放列表函数，该函数中将传入的软连接转为了真实路径进行保存；
解决办法：PlayerWidget::play播放函数中，首先将传入的软连接转为真实的路径，然后将真实路径传给后续调用的两个函数。
Log: 修复bug139163
Bug: https://pms.uniontech.com/bug-view-139163.html
/review
@myk1343 @feeengli
> fix: 修复bug139163

- src/widgets/platform/platform_volumeslider.cpp
- src/widgets/volumeslider.cpp
初始化时影院非静音模式不设置dbus音量
Log: 初始化时影院非静音模式不设置dbus音量
Bug: https://pms.uniontech.com/bug-view-151809.html
> fix: bug 151809 初始化时影院非静音模式不设置dbus音量

- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/toolbox_proxy.cpp
修复屏幕缩放设置为1.25时，影院进度条预览问题
Log: 修复屏幕缩放设置为1.25时，影院进度条预览问题
Bug: https://pms.uniontech.com/bug-view-140543.html
https://pms.uniontech.com/bug-view-145769.html
> fix: bug140543 145769 修复屏幕缩放设置为1.25, 1.75倍时，影院进度条预览问题

- src/libdmr/playlist_model.cpp
In https://github.com/FFmpeg/FFmpeg/commit/e67e02d15672a87da1b0566e197a1e19dc7e1e33 avcodec.h is no longer included by avformat.h. Let's include it explicitly to fix build on ffmpeg 5+.
Log: Fix compatibility with ffmpeg 5+
> fix: compatibility with ffmpeg 5+

- src/widgets/volumeslider.cpp
取消静音时同步设置dbus
Bug: https://pms.uniontech.com/bug-view-157681.html
Log: 修复部分已知问题
> fix: 修复修改音量未取消静音问题

- src/widgets/volumeslider.cpp
静音后不再设置dbus
Bug: https://pms.uniontech.com/bug-view-158533.html
Log: 修复部分已知问题
> fix: 修复播放器静音问题

- src/libdmr/compositing_manager.cpp
海光N卡下使用gpu渲染
Bug: https://pms.uniontech.com/bug-view-151257.html
Log: 修复部分已知问题
> fix: 修复海光s3唤醒后退出慢问题

- src/libdmr/compositing_manager.cpp
在libdmr中不使用影院提供的gsetting接口
Bug: https://pms.uniontech.com/bug-view-163343.html
Log: 修复部分已知问题
> fix: 修复影院卸载后预览失败问题

- tests/deepin-movie/common/test_mainwindow.cpp
https://github.com/linuxdeepin/developer-center/issues/3455 修复test_mainwindow.cpp 1219行函数定义错误的bug
> modify bug #3455

- src/backends/mediaplayer/qtplayer_proxy.cpp
修复GStreamer下重复播放起点时间不对的问题和异常图片渲染崩溃的问题
Log: 修复GStreamer下重复播放起点时间不对的问题和异常图片渲染崩溃的问题
/reivew
@pengfeixx @myk1343 @wyu71
> fix: 修复GStreamer下重复播放起点时间不对的问题和异常图片渲染崩溃的问题

- src/common/platform/platform_mainwindow.cpp
优化窗口离开事件，不立刻隐藏窗口标题栏
Bug: https://pms.uniontech.com/bug-view-170807.html
Log: 修复部分已知问题
> fix: 修复兆芯大板拖动闪烁问题

- src/common/mainwindow.cpp
修复全屏迷你模式切换时，显示影院窗口较慢
Bug: https://pms.uniontech.com/bug-view-178561.html
Log: 修复全屏迷你模式切换时，显示影院窗口较慢
> fix: 178561 全屏模式切换到迷你模式，切换过程中有2s不显示影院窗口

- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/toolbox_proxy.cpp
修复影院播放视频后，点击投屏，再点击全屏返回后 ，投屏图标空白。
Bug: https://pms.uniontech.com/bug-view-180357.html
Log: 修复影院播放视频后，点击投屏，再点击全屏返回后 ，投屏图标空白。
> fix: 修复bug 180357

- src/libdmr/player_engine.cpp
清空列表时将列表内所有的记录清除
Bug: https://pms.uniontech.com/bug-view-181745.html
Log: 修复部分已知问题
> fix: 修复清空列表未清除播放记录

- src/backends/mpv/mpv_proxy.cpp
- src/libdmr/compositing_manager.cpp
兆芯KX6000强制使用vaapi解码及输出
Bug: https://pms.uniontech.com/bug-view-197463.html
Log: 修复部分已知问题
> fix: 修复兆芯KX6000硬解码播放卡顿问题

- src/libdmr/filefilter.cpp
m3u8文件为无效文件，不播放
Bug: https://pms.uniontech.com/bug-view-165611.html
Log: 修复部分已知问题
> fix: 修复m3u8文件播放卡死问题

- src/widgets/mircastwidget.cpp
- src/widgets/mircastwidget.h
修复投屏，pc2投屏后把pc1投屏状态清除
Bug: https://pms.uniontech.com/bug-view-159991.html
Log: 修复投屏，pc2投屏后把pc1投屏状态清除
> fix: 修复投屏，pc2投屏后把pc1投屏状态清除

- src/common/mainwindow.cpp
- src/common/mainwindow.h
使用DBus接口获取当前CPU型号，并判断是否为PANGU M900
Log: 修复PANGU M900的CPU型号，切换迷你模式闪退的问题
Bug: https://pms.uniontech.com/bug-view-204685.html
> fix: 修复PANGU M900的CPU型号，切换迷你模式闪退的问题

- src/libdmr/playlist_model.h
DGuiApplicationHelper has been moved into DGui, so using Dtk::Gui instead of Dtk::Widget
Log: fix build error
> fix: build error

- src/common/platform/platform_mainwindow.cpp
> fix: 修复全屏时间控件异常问题

- src/common/mainwindow.cpp
修复wayland从迷你模式切回正常模式无法缩放大小问题，应用规避操作
Bug: https://pms.uniontech.com/bug-view-212207.html
Log: 修复部分已知问题
> fix: 修复wayland下迷你模式异常

- src/common/mainwindow.cpp
Log: Constraints on mouse wheel distance outliers to keep the m_iAngLeDelta parameter in the appropriate range.
Bug: https://pms.uniontech.com/zentao/bug-view-217945.html
> fix: Volume abnormal when screen is flipped

- src/backends/mpv/mpv_proxy.cpp
- src/libdmr/compositing_manager.cpp
修改loongarch64集显渲染方式
Bug: https://pms.uniontech.com/bug-view-220641.html
Log: 修改loongarch64集显渲染方式
> fix: 修改loongarch64集显渲染方式

- src/widgets/platform/platform_playlist_widget.cpp
- src/widgets/platform/platform_playlist_widget.h
- src/widgets/playlist_widget.cpp
- src/widgets/playlist_widget.h
若找不到视频 则给用户友好提示
Log: 正常播放视频  若找不到视频 则给用户友好提示
Bug: https://pms.uniontech.com/bug-view-218273.html
> fixed: 影院循环播放10个smb上的视频一段时间后，点击播放按钮或点击列表中的视频均无法播放

- src/common/mainwindow.cpp
- src/common/mainwindow.h
- src/common/platform/platform_mainwindow.cpp
- src/common/platform/platform_mainwindow.h
- src/widgets/platform/platform_playlist_widget.cpp
- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/platform/platform_toolbox_proxy.h
- src/widgets/playlist_widget.cpp
- src/widgets/playlist_widget.h
- src/widgets/toolbox_proxy.cpp
- src/widgets/toolbox_proxy.h
紧凑模式下，打开播放列表后点击全屏按钮，播放列表显示异常
Log: 修改紧凑模式下播放列表的高度为动态高度
> fixed: 紧凑模式下，打开播放列表后点击全屏按钮，播放列表显示异常

- src/libdmr/compositing_manager.cpp
修复m900查看缩略图时,播放卡顿问题
Bug: https://pms.uniontech.com/bug-view-228541.html
Log: 修复m900查看缩略图时,播放卡顿问题
> fix: 修复m900查看缩略图时,播放卡顿问题

- src/widgets/toolbox_proxy.cpp
修复初始化进度条中的缩略图时闪现黑色条纹
Bug: https://pms.uniontech.com/bug-view-229439.html Log: 修复初始化进度条中的缩略图时闪现黑色条纹
> fix: 修复初始化进度条中的缩略图时闪现黑色条纹

- src/libdmr/playlist_model.cpp
修复在播放完第一段视频的时候,自动播放第二段视频的刚开始会出现断层画面
Bug: https://pms.uniontech.com/bug-view-234981.html
Log: 修复在播放完第一段视频的时候,自动播放第二段视频的刚开始会出现断层画面
> fix: 修复在播放完第一段视频的时候,自动播放第二段视频的刚开始会出现断层画面

- debian/changelog
Bump version to 5.10.41
PR:
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/410
Log: Bump version to 5.10.41
> chore: Bump version to 5.10.41

- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
在X11部分场景下, 直接使用showMaximized()可能无效, X11
使用协议不理解全屏窗口(Qt帮助). 旧版代码在最大化前调用
showNormal(), 会导致窗口状态变更两次, 使得界面闪烁.
调整和 mainwindow.cpp 保持一致, 全屏时保留Maximized状态
信息, 以正常触发全屏的切换.
移除手动设置窗口大小, 由窗管统一管理.
Log: 修复最大化/全屏切换时组件闪烁问题
Bug: https://pms.uniontech.com/bug-view-239775.html
> fix: 修复最大化/全屏切换时组件闪烁

- debian/changelog
Bump version to 5.10.42
PR:
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/414
Log: Bump version to 5.10.42
> chore: Bump version to 5.10.42

- src/common/diskcheckthread.cpp
Log: dont use </usr/include/linux/cdrom.h>
不应该 include 绝对路径
> chore: dont use </usr/include/linux/cdrom.h>

- src/widgets/platform/platform_notification_widget.cpp
窗口激活时同样判断窗口层叠，防止非顶层激活
Bug: https://pms.uniontech.com/bug-view-228787.html
Log: 修复部分已知问题
> fix: 修复消息提示框问题

- src/common/mainwindow.cpp
在拖拽进度等操作，高占用播放视频时，使用右键菜单操作
可能使 wayland 未能正确切换窗体，导致 surface destroy，
wayland 报告错误，程序闪退。
修改为执行 show 操作前，主动创建上下文，
生成 surface 以正常填入数据。
Log: 修复wayland下迷你模式闪退问题
Bug: https://pms.uniontech.com/bug-view-241865.html
> fix: wayland下迷你模式闪退问题

- debian/changelog
Bump version to 5.10.44
PR:
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/418
Log: Bump version to 5.10.44
> chore: Bump version to 5.10.44

- src/main.cpp
应用涉及 GPU 加速，目前合成器重连暂未完整支持，
移除 QT_WAYLAND_RECONNECT 环境变量，不参与合成
器崩溃重连。
Log: 规避部分已知问题
Task: https://pms.uniontech.com/task-view-326583.html
> feat: 不参与合成器崩溃重连

- debian/changelog
Bump version to 5.10.47
PR:
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/430
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/431
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/432
Log: Bump version to 5.10.47
> chore: Bump version to 5.10.47

- src/backends/mediaplayer/qtplayer_glwidget.cpp
- src/backends/mediaplayer/qtplayer_glwidget.h
- src/backends/mpv/mpv_glwidget.cpp
- src/backends/mpv/mpv_glwidget.h
GL绘制代码中使用自定FBO和裁剪圆角部分绑定,
wayland下需要使用自定FBO以避免出现闪黑屏,
而全屏下不需要裁剪圆角。
为兼容两种场景，将自定FBO和绘制圆角改为两个
Flag变量控制，全屏/最大化时，使用自定FBO绘制
也不会绘制圆角，其它流程保持原样。
* 在(非)组合模式下，切换迷你模式、窗口模式、 全屏测试
关联Bug:
https://pms.uniontech.com/bug-view-225881.html
https://pms.uniontech.com/bug-view-196087.html
Log: 修复部分播放显示问题
Bug: https://pms.uniontech.com/bug-view-247735.html
> fix: 全屏播放时存在裁剪圆角

- src/common/platform/platform_mainwindow.cpp
非组合模式下暂停图标设置了Tool标志，
调整为最小化时不触发动画，播放过程的
动画也隐藏。
Log: 修复暂停图标在最小化时仍显示的问题
Bug: https://pms.uniontech.com/bug-view-247791.html
> fix: 暂停图标在最小化时仍显示

- src/backends/mpv/mpv_proxy.cpp
HW机型在自动模式检测为软解码，同预期不符
目前探测HW机型途径有DConfig、gpuinfo。但均
存在设备更新不能及时处理。调整为在影院判断
设备类型，并切换硬解码
Log: 修复部分解码问题
Bug: https://pms.uniontech.com/bug-view-249087.html
> fix: HW机型硬解码探测调整

- src/common/dbus_adpator.cpp
- src/common/platform/platform_dbus_adpator.cpp
修复从相机点击播放视频打开影院,窗口层级显示不对
Bug: https://pms.uniontech.com/bug-view-248689.html
Log: 修复从相机点击播放视频打开影院,窗口层级显示不对
> fix: 修复从相机点击播放视频打开影院,窗口层级显示不对

- debian/changelog
Bump version to 5.10.49
PR:
* https://github.com/linuxdeepin/deepin-movie-reborn/pull/445
Log: Bump version to 5.10.49
> chore: Bump version to 5.10.49

- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
判断音量未修改时不开启事件循环
Bug: https://pms.uniontech.com/bug-view-251965.html
Log: 修复部分已知问题
> fix: 修复影院无法退出问题

- src/libdmr/gstutils.cpp
the parseFileByGst() function use strcpy causing the overflow risk.
Bug: https://pms.uniontech.com/bug-view-253945.html
Log: 修复部分已知问题
> fix: the overflow bug of deepin-movie

- src/common/mainwindow.cpp
应用层检测到屏幕后对应用进行移动
Bug: https://pms.uniontech.com/bug-view-252617.html
Log: 应用层检测到屏幕后对应用进行移动
> fix: 应用层检测到屏幕后对应用进行移动

- debian/control
- src/common/dmr_settings.cpp
- src/common/platform/platform_thumbnail_worker.cpp
- src/common/platform/platform_thumbnail_worker.h
- src/common/thumbnail_worker.cpp
- src/common/thumbnail_worker.h
- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/platform/platform_toolbox_proxy.h
- src/widgets/toolbox_proxy.cpp
- src/widgets/toolbox_proxy.h
This reverts commit bd46423858a01b6062759b399d9c895cc8bafde2.
> Revert "fix: Remove Thumbnailer dependency (#473)"

- src/libdmr/playlist_model.cpp
- src/libdmr/playlist_model.h
- src/widgets/toolbutton.h
ffmpeg api error
Log: compile error
> fix: compile error

- src/libdmr/compositing_manager.cpp
Arise1020 显卡使用vaapi渲染
Bug: https://pms.uniontech.com/bug-view-266595.html
Log: Arise1020 显卡使用vaapi渲染
> fix: Arise1020 显卡使用vaapi渲染，修复偶尔音频无声问题

- src/libdmr/compositing_manager.cpp
Fixed the issue that MPV library could not be found
Bug: https://pms.uniontech.com/bug-view-265013.html
Log: Fixed the issue that MPV library could not be found
> fix: Fixed the issue that MPV library could not be found

- src/common/platform/platform_mainwindow.cpp
修复全屏后切换迷你模式，右键菜单中的全屏勾选状态显示错误
Bug: https://pms.uniontech.com/bug-view-262887.html
Log: 修复全屏后切换迷你模式，右键菜单中的全屏勾选状态显示错误
> fix: 修复全屏后切换迷你模式，右键菜单中的全屏勾选状态显示错误

- src/backends/mpv/mpv_proxy.cpp
- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
- src/libdmr/compositing_manager.cpp
- src/libdmr/utils.cpp
- src/libdmr/utils.h
- src/main.cpp
- src/widgets/toolbox_proxy.cpp
Command execution rectification
Log: Command execution rectification
> fix: Command execution rectification

- .gitignore
- arm64/linglong.yaml
- examples/test/CMakeLists.txt
- install_dep
- linglong.yaml
- src/CMakeLists.txt
- src/backends/mpv/mpv_glwidget.cpp
- src/backends/mpv/mpv_proxy.cpp
- src/backends/mpv/mpv_proxy.h
- src/common/hwdec_probe.cpp
- src/common/platform/platform_thumbnail_worker.cpp
- src/common/platform/platform_thumbnail_worker.h
- src/common/sysutils.cpp
- src/common/sysutils.h
- src/common/thumbnail_worker.cpp
- src/common/thumbnail_worker.h
- src/libdmr/CMakeLists.txt
- src/libdmr/compositing_manager.cpp
- src/libdmr/compositing_manager.h
- src/libdmr/filefilter.cpp
- src/libdmr/filefilter.h
- src/libdmr/gstutils.cpp
- src/libdmr/gstutils.h
- src/libdmr/playlist_model.cpp
- src/libdmr/playlist_model.h
- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/toolbox_proxy.cpp
Merge linglong changes and fix runtime issue, enable to build linglong pakage.
Log: Adapt linglong.
> chore: Adapt linglong

- src/backends/mpv/mpv_proxy.cpp
修复兆芯右键硬解不能旋转
Log: 修复兆芯右键硬解不能旋转
Bug: https://pms.uniontech.com/bug-view-285669.html
> fix: 修复兆芯右键硬解不能旋转

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
Update changelog
Log: Update changelog
> Chore: Update changelog

- src/backends/mpv/mpv_proxy.cpp
Fixed the audio issue under Treeland
Log: Fixed the audio issue under Treeland
> fix: Fixed the audio issue under Treeland

- src/common/dbus_adpator.cpp
- src/common/dbus_adpator.h
- src/common/platform/platform_dbus_adpator.cpp
- src/common/platform/platform_dbus_adpator.h
Fixed the issue that the camera failed to be turned on
Log: Fixed the issue that the camera failed to be turned on
> fix: Fixed the issue that the camera failed to be turned on

- src/common/platform/platform_mainwindow.cpp
修复移动播放窗口后，点击还原按钮无响应
Bug: https://pms.uniontech.com/bug-view-293141.html
Log: 修复移动播放窗口后，点击还原按钮无响应
> fix: 修复移动播放窗口后，点击还原按钮无响应

- src/common/platform/platform_mainwindow.cpp
迷你模式下规避防止窗管菜单可以改变大小
Bug: https://pms.uniontech.com/bug-view-293145.html
Log: 迷你模式下规避防止窗管菜单可以改变大小
> fix: 迷你模式下规避防止窗管菜单可以改变大小

- src/backends/mpv/mpv_proxy.cpp
- src/libdmr/player_engine.cpp
- src/widgets/mircastwidget.cpp
- src/widgets/platform/platform_toolbox_proxy.cpp
- src/widgets/toolbox_proxy.cpp
修复movie coredump
Bug: https://pms.uniontech.com/bug-view-299235.html
Log: 修复movie coredump
> fix: 修复movie coredump

- src/backends/mpv/mpv_glwidget.cpp
- src/backends/mpv/mpv_proxy.cpp
- src/libdmr/compositing_manager.cpp
- src/libdmr/compositing_manager.h
Fixed the issue that OpenGL could not be played
Log: Fixed the issue that OpenGL could not be played
> fix: Fixed the issue that OpenGL could not be played

- src/backends/mpv/mpv_proxy.cpp
- src/common/mainwindow.cpp
修复切换显示内存泄漏问题
Bug: https://pms.uniontech.com/bug-view-301043.html
Log: 修复切换显示内存泄漏问题
> fix: 修复切换显示内存泄漏问题

- src/backends/mpv/mpv_glwidget.cpp
优化显示切换时内存泄漏，及时释放显示纹理资源
Bug: https://pms.uniontech.com/bug-view-287761.html
Log: 优化显示切换时内存泄漏，及时释放显示纹理资源
> fix: 优化显示切换时内存泄漏，及时释放显示纹理资源

- src/common/mainwindow.cpp
wayland下防止resize时改变窗口坐标，由窗管自己完成
Bug: https://pms.uniontech.com/bug-view-300849.html
Log: wayland下防止resize时改变窗口坐标，由窗管自己完成
> fix: wayland下防止resize时改变窗口坐标，由窗管自己完成

- src/backends/mpv/mpv_proxy.cpp
音频参数 pulse-allow-suspended=yes
Bug: https://pms.uniontech.com/bug-view-282287.html
Log: 加入音频参数 pulse-allow-suspended=yes
> fix: 加入音频参数 pulse-allow-suspended=yes

- deploy_dep
- loong64/linglong.yaml
The crash is caused by the failure to load the libmpv.so library, because its dependency libatomic.so.1 is included in base develop module but not in binary module. The solution is to manually install the libatomic.so.1 library and its dependencies.
Log: Fix app crash on loong64
> fix: Fix app crash on loong64

- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
dbus信号不可控，不同平台使用的代码不同，platform_mainwindow上在休眠和锁定情况下都会切换状态，dbus信号异常时，状态也会异常。 而mainwindow中只会在锁定情况下切换状态，所以不会异常，该提交没有同步到platform_mainwindow。
log: 统一不同平台表现，及变更需求为：待机重启后，暂停播放。
bug: https://pms.uniontech.com/bug-view-291039.html
> fix: 不同平台下，睡眠后播放状态不一致的问题

- src/accessibility/ac-deepin-movie-define.h
- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
- src/widgets/mircastwidget.cpp
- tests/deepin-movie/common/test_mainwindow.cpp
- Rename MIRCAST_DISCONNECTIONED to MIRCAST_DISCONNECTED
- Fix spelling error in Miracast disconnection constant
- Update all references to use correct spelling
This commit corrects the typo in the Miracast disconnection macro name and updates all related code references for consistency.
log: fix spelling error
> style: fix typo in MIRCAST_DISCONNECTIONED macro

- src/accessibility/ac-deepin-movie-define.h
- src/common/mainwindow.cpp
- src/common/platform/platform_mainwindow.cpp
- src/widgets/mircastwidget.cpp
- tests/deepin-movie/common/test_mainwindow.cpp
The correct past tense and past participle of the verb ​​"succeed"​​ is ​​"succeeded"​​, not "succssed".
Log: fix spelling error
> style: fix spelling error of SUCCEEDED
